force-app/main/default/objects/Construction__c/Construction__c.object-meta.xml
<CustomObject>
    <label>Construction</label>
    <nameField>
        <label>Construction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Construction__c/fields/Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Billing_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Constructions (Billing Company)</relationshipLabel>
    <relationshipName>Constructions1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction__c/fields/Owner_Company__c.field-meta.xml
<CustomField>
    <fullName>Owner_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Owner Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Constructions</relationshipLabel>
    <relationshipName>Constructions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Building</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Restoration</fullName>
            </value>
            <value>
                <fullName>Infrastructure Creation</fullName>
            </value>
            <value>
                <fullName>Infrastructure Renewal</fullName>
            </value>
            <value>
                <fullName>Infrastructure Connection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Construction__c/fields/Work_Breakdown_Structure__c.field-meta.xml
<CustomField>
    <fullName>Work_Breakdown_Structure__c</fullName>
    <label>Work Breakdown Structure</label>
    <referenceTo>Work_Breakdown_Structure__c</referenceTo>
    <relationshipLabel>Constructions</relationshipLabel>
    <relationshipName>Constructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Construction__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>true</active>
    <label>Building</label>
</RecordType>

force-app/main/default/objects/Product2__c/Product2__c.object-meta.xml
<CustomObject>
    <label>Product2</label>
    <nameField>
        <label>Product Name2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price(in one hour)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/Work_Breakdown_Structure__c.object-meta.xml
<CustomObject>
    <label>Work Breakdown Structure</label>
    <nameField>
        <label>Work Breakdown Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Breakdown Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Record type is not Engineering Unit or Sub-Contractor</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Engineering Unit, Sub-Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Construction__c.field-meta.xml
<CustomField>
    <fullName>Construction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Construction</label>
    <referenceTo>Construction__c</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/IsSynced__c.field-meta.xml
<CustomField>
    <fullName>IsSynced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSynced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/Work_Breakdown_Structure_Item__c.object-meta.xml
<CustomObject>
    <label>Work Breakdown Structure Item</label>
    <nameField>
        <label>Work Breakdown Structure Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Breakdown Structure Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Engineering Unit, Sub-Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Breakdown Structure Items</relationshipLabel>
    <relationshipName>Work_Breakdown_Structure_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
                <default>true</default>
                <label>Hours</label>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Work</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2__c.Type__c</field>
            <operation>equals</operation>
            <value>Work</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2__c</referenceTo>
    <relationshipLabel>Work Breakdown Structure Items (Work)</relationshipLabel>
    <relationshipName>Work_Breakdown_Structure_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/fields/Work_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Work_Assignment__c</fullName>
    <label>Work Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Breakdown Structure Items</relationshipLabel>
    <relationshipName>Work_Breakdown_Structure_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure_Item__c/fields/Work_Breakdown_Structure__c.field-meta.xml
<CustomField>
    <fullName>Work_Breakdown_Structure__c</fullName>
    <label>Work Breakdown Structure</label>
    <referenceTo>Work_Breakdown_Structure__c</referenceTo>
    <relationshipLabel>Work Breakdown Structure Items</relationshipLabel>
    <relationshipName>Work_Breakdown_Structure_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerTest.cls
@isTest
private class OpportunityTriggerTest {
	public class IvalidStageException extends Exception {
	}
	@testSetup
	static void setupRecords() {
		Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
			.get('Engineering_Unit')
			.getRecordTypeId();
		Account acct = new Account(Name = 'TestAccount', RecordTypeId = accRecordTypeId);
		insert acct;

		Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
			.get('Worker')
			.getRecordTypeId();
		Contact con = new Contact(
			LastName = 'TestContact',
			Email = 'vip.nepochelovich@gmail.com',
			RecordTypeId = conRecordTypeId,
			Level__c = 'E',
			AccountId = acct.Id
		);
		insert con;

		Id consRecordTypeId = Schema.SObjectType.Construction__c.getRecordTypeInfosByDeveloperName()
			.get('Building')
			.getRecordTypeId();
		Construction__c cons = new Construction__c(
			Name = 'TestConstruction',
			Billing_Company__c = acct.Id,
			Owner_Company__c = acct.Id,
			RecordTypeId = consRecordTypeId
		);
		insert cons;

		Opportunity oppNew = new Opportunity(
			Name = 'OpportunityNew',
			StageName = Constants.OPP_STAGE_NEW,
			CloseDate = System.today().addMonths(1),
			Decision_Maker__c = con.id
		);
		insert oppNew;

		Opportunity oppQuoteSent = new Opportunity(
			Name = 'OpportunityQuoteSent',
			StageName = Constants.OPP_STAGE_QUOTE_SENT,
			CloseDate = System.today().addMonths(1),
			Decision_Maker__c = con.id
		);
		insert oppQuoteSent;

		Work_Breakdown_Structure__c wbs = new Work_Breakdown_Structure__c(
			Name = 'TestBreakdown',
			Status__c = 'Draft',
			Opportunity__c = oppNew.Id,
			Construction__c = cons.Id,
			Account__c = acct.Id
		);
		insert wbs;
		wbs.Status__c = Constants.WBS_STATUS_SENT;
		update wbs;

		Work_Breakdown_Structure__c wbsSynced = new Work_Breakdown_Structure__c(
			Name = 'TestBreakdownSynced',
			Status__c = 'Draft',
			Opportunity__c = oppQuoteSent.Id,
			Construction__c = cons.Id,
			Account__c = acct.Id,
			IsSynced__c = true
		);
		insert wbsSynced;

		oppQuoteSent.Work_Breakdown_Structure__c = wbsSynced.id;
		update oppQuoteSent;

		Product2__c prod = new Product2__c(Name = 'TestProduct', Type__c = 'Work', Price__c = 70);
		insert prod;

		Work_Breakdown_Structure_Item__c wbsi = new Work_Breakdown_Structure_Item__c(
			Name = 'TestItem',
			Work__c = prod.id,
			Unit_Of_Measure__c = 'Hours',
			Quantity__c = 4,
			Work_Breakdown_Structure__c = wbs.Id,
			Account__c = acct.id,
			Work_Assignment__c = con.id
		);
		insert wbsi;
	}

	@isTest
	static void testChangeOnQuoteSentStageTrue() {
		Opportunity opp = [SELECT StageName FROM Opportunity WHERE Name = 'OpportunityQuoteSent'];
		opp.StageName = 'Draft Quote';
		update opp;
		Work_Breakdown_Structure__c wbs = [
			SELECT Status__c
			FROM Work_Breakdown_Structure__c
			WHERE Name = 'TestBreakdownSynced'
		];

		System.assertEquals(Constants.WBS_STATUS_REJECTED, wbs.Status__c);
	}

	@isTest
	static void testOppStageChangeTrue() {
		Opportunity opp = [SELECT StageName FROM Opportunity WHERE Name = 'OpportunityQuoteSent'];
		opp.StageName = Constants.OPP_STAGE_CLOSED_WON;

		System.assertEquals(true, Database.update(opp).isSuccess());
	}

	@isTest
	static void testOppStageChangeFalse() {
		Opportunity opp = [SELECT StageName FROM Opportunity WHERE Name = 'OpportunityNew'];
		try {
			opp.StageName = Constants.OPP_STAGE_CLOSED_WON;
			update opp;
			throw new IvalidStageException('An exception should have been thrown by the trigger but was not.');
		} catch (Exception e) {
			Boolean expectedExceptionThrown = e.getMessage()
				.contains('You can only change Quote Sent and Negotiation status on Closed Won.');

			System.assertEquals(true, expectedExceptionThrown);
		}
	}
}