force-app/main/default/objects/Construction__c/Construction__c.object-meta.xml
<CustomObject>
    <label>Construction</label>
    <nameField>
        <label>Construction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Construction__c/fields/Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Billing_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Constructions (Billing Company)</relationshipLabel>
    <relationshipName>Constructions1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction__c/fields/Owner_Company__c.field-meta.xml
<CustomField>
    <fullName>Owner_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Owner Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Constructions</relationshipLabel>
    <relationshipName>Constructions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction__c/fields/Work_Breakdown_Structure__c.field-meta.xml
<CustomField>
    <fullName>Work_Breakdown_Structure__c</fullName>
    <label>Work Breakdown Structure</label>
    <referenceTo>Work_Breakdown_Structure__c</referenceTo>
    <relationshipLabel>Constructions</relationshipLabel>
    <relationshipName>Constructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Construction__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>true</active>
    <label>Building</label>
</RecordType>

force-app/main/default/objects/Work_Breakdown_Structure__c/Work_Breakdown_Structure__c.object-meta.xml
<CustomObject>
    <label>Work Breakdown Structure</label>
    <nameField>
        <label>Work Breakdown Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Breakdown Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Record type is not Engineering Unit or Sub-Contractor</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Engineering Unit, Sub-Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Construction__c.field-meta.xml
<CustomField>
    <fullName>Construction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Construction</label>
    <referenceTo>Construction__c</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/IsSynced__c.field-meta.xml
<CustomField>
    <fullName>IsSynced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSynced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeOnQuoteSentStageTest.cls
@isTest
private class ChangeOnQuoteSentStageTest {
    @testSetup static void setupRecords() {
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Engineering_Unit').getRecordTypeId();
        Account acct = new Account(Name='TestAccount', RecordTypeId = accRecordTypeId);
        insert acct;
        
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Worker').getRecordTypeId();
        Contact con = new Contact(LastName='TestContact', Email = 'vip.nepochelovich@gmail.com', RecordTypeId = conRecordTypeId, Level__c='E', 	AccountId=acct.Id);
        insert con;
        
        Id consRecordTypeId = Schema.SObjectType.Construction__c.getRecordTypeInfosByDeveloperName().get('Building').getRecordTypeId();
        Construction__c cons = new Construction__c(Name='TestConstruction',
                                                   Billing_Company__c = acct.Id,
                                                   Owner_Company__c = acct.Id,
                                                  RecordTypeId = consRecordTypeId);
        insert cons;
        
        Opportunity opp = new Opportunity(Name='NewOpportunity',
                                          StageName='Quote Sent',
                                          CloseDate=System.today().addMonths(1),
                                          Decision_Maker__c = con.id);
        insert opp;
        
        Work_Breakdown_Structure__c wbs = new Work_Breakdown_Structure__c(Name='TestBreakdown',
                                                                          Status__c = 'Draft',
                                                                          Opportunity__c = opp.Id,
                                                                         Construction__c = cons.Id,
                                                                         Account__c = acct.Id,
                                                                         IsSynced__c=True);
        insert wbs;
        opp.StageName = 'Draft Quote';
        update opp;
        
	}
    @isTest static void testChangeOnQuoteSentStageTrue() {
        Work_Breakdown_Structure__c wbs = [SELECT Status__c FROM Work_Breakdown_Structure__c WHERE Name='TestBreakdown'];
        System.assertEquals('Rejected', wbs.Status__c);
    }
}