force-app/main/default/objects/Work_Breakdown_Structure__c/Work_Breakdown_Structure__c.object-meta.xml
<CustomObject>
    <label>Work Breakdown Structure</label>
    <nameField>
        <label>Work Breakdown Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Breakdown Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/IsSynced__c.field-meta.xml
<CustomField>
    <fullName>IsSynced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSynced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Breakdown Structures</relationshipLabel>
    <relationshipName>Work_Breakdown_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Work_Breakdown_Structure_Item__c.Total_Amount_Price__c</summarizedField>
    <summaryForeignKey>Work_Breakdown_Structure_Item__c.Work_Breakdown_Structure__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/WorkBreakdownStructureTriggerHandler.cls
public class WorkBreakdownStructureTriggerHandler implements ITriggerHandler {
	private static Boolean triggerDisabled = false;

	public void disableTrigger() {
		triggerDisabled = true;
	}
	public void enableTrigger() {
		triggerDisabled = false;
	}

	public Boolean isTriggerEnabled() {
		if (triggerDisabled) {
			return false;
		} else {
			return true;
		}
	}

	public void beforeUpdate(
		Map<Id, SObject> newItemsMap,
		Map<Id, SObject> oldItemsMap,
		List<SObject> newItems,
		List<SObject> oldItems
	) {
		for (Work_Breakdown_Structure__c wbs : (List<Work_Breakdown_Structure__c>) newItems) {
			if (wbs.Status__c == Constants.WBS_STATUS_SENT && wbs.Opportunity__c != null) {
				wbs.IsSynced__c = true;
			}
		}
	}

	public void afterUpdate(
		Map<Id, SObject> newItemsMap,
		Map<Id, SObject> oldItemsMap,
		List<SObject> newItems,
		List<SObject> oldItems
	) {
		List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
		Set<Id> oppIds = new Set<Id>();
		for (Work_Breakdown_Structure__c wbs : (List<Work_Breakdown_Structure__c>) newItems) {
			if (wbs.Status__c == Constants.WBS_STATUS_SENT && wbs.Opportunity__c != null) {
				oppIds.add(wbs.Opportunity__c);
			}
		}
		Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(
			[SELECT Amount, Decision_Maker__r.LastName, id FROM Opportunity WHERE id IN :oppIds]
		);
		for (Work_Breakdown_Structure__c wbs : (List<Work_Breakdown_Structure__c>) newItems) {
			if (wbs.Status__c == Constants.WBS_STATUS_SENT && wbs.Opportunity__c != null) {
				Opportunity opp = oppMap.get(wbs.Opportunity__c);
				opp.Amount = wbs.Total_Amount__c;
				opp.Work_Breakdown_Structure__c = wbs.Id;
				update opp;
				mailList.add(EmailUtility.putEmailInfoOnTemplate(opp.Decision_Maker__r.LastName, Contact.SObjectType));
			}
		}
		EmailUtility.sendEmail(mailList);
	}

	public void beforeInsert(List<SObject> newItems) {
	}

	public void beforeDelete(Map<Id, SObject> oldItemsMap) {
	}

	public void afterDelete(Map<Id, SObject> oldItemsMap) {
	}

	public void afterUndelete(Map<Id, SObject> oldItemsMap) {
	}

	public void afterInsert(Map<Id, SObject> newItemsMap) {
	}
}